### ISSUE TITLE
Update backend to support Sigma Correlations

### ISSUE THREAD

**Issue by kelnage** [grafana/pySigma-backend-loki#124]
The [latest release](https://github.com/SigmaHQ/pySigma/releases/tag/v0.11.0) of pySigma includes a feature known as [Sigma Correlations](https://github.com/SigmaHQ/pySigma/commit/a848c56bae9f9cedb703397b220700d5696a3b36) (documented in the [next version](https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md) of the Sigma specification), which allows Sigma rules to look at a larger number of log events and use them to determine whether to produce an alert or not.

We should be able to achieve most (if not all) of the core Correlations functionality via LogQL's [metric queries](https://grafana.com/docs/loki/latest/query/metric_queries/) support.
```[tasklist]
### Tasks
- [x] Read Sigma Correlations [PR](https://github.com/SigmaHQ/pySigma/commit/a848c56bae9f9cedb703397b220700d5696a3b36) to understand what the change does
- [x] Read the [specification doc](https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md) of the Sigma Correlations (aka. meta rules)
- [x] Read LogQL [metric query doc](https://grafana.com/docs/loki/latest/query/metric_queries/) to understand and investigate supported queries that map with Sigma Correlations
- [x] Implement the feature
- [x] Write tests
- [ ] Release a new version
- [ ] Add supported [`capabilities`](https://github.com/SigmaHQ/pySigma/blob/ca1a950e34c9d69241c972954618a1e1cad2adeb/tests/test_plugins.py#L96-L99) to the [pySigma-plugin-directory](https://github.com/SigmaHQ/pySigma-plugin-directory) repo
```

**Comment by kelnage** [comment]
[This PR](https://github.com/grafana/sigma-internal/pull/7) provides an example correlation rule that could be used for testing this feature once it is implemented.

**Comment by mostafa** [comment]
@kelnage As per our discussion yesterday, I assigned this to you.
