### ISSUE TITLE
Investigate mapping of LogQL metric queries to Sigma Correlation

### ISSUE THREAD

**Issue by mostafa** [grafana/pySigma-backend-loki#161]
This ticket involves reading the documentations by Sigma and Loki LogQL and try to create a plan of the supported queries to be implemented in pySigma-backend-loki.

```[tasklist]
### Tasks
- [ ] Read Sigma Correlations [PR](https://github.com/SigmaHQ/pySigma/commit/a848c56bae9f9cedb703397b220700d5696a3b36) to understand what the change does
- [ ] Read the [specification doc](https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md) of the Sigma Correlations (aka. meta rules)
- [ ] Read LogQL [metric query doc](https://grafana.com/docs/loki/latest/query/metric_queries/) to understand and investigate supported queries that map with Sigma Correlations
```

**Comment by mostafa** [comment]
Closed in favor of #124.
