### ISSUE TITLE
Implement Sigma Correlations to convert Sigma correlation rules to supported metric queries

### ISSUE THREAD

**Issue by mostafa** [grafana/pySigma-backend-loki#162]
This implementation ticket follows the [investigation ticket](#161) that maps the Sigma correlation rules to supported metric queries.

```[tasklist]
### Tasks
- [ ] Implement the feature
- [ ] Write tests
- [ ] Release a new version
- [ ] Add supported [`capabilities`](https://github.com/SigmaHQ/pySigma/blob/ca1a950e34c9d69241c972954618a1e1cad2adeb/tests/test_plugins.py#L96-L99) to the [pySigma-plugin-directory](https://github.com/SigmaHQ/pySigma-plugin-directory) repo
```

**Comment by kelnage** [comment]
Duplicate of #124?

**Comment by mostafa** [comment]
@kelnage I thought of #124 as an epic and I broke it down into two separate spike (investigation) and implementation tickets, just like we do for many other epics.

**Comment by kelnage** [comment]
During our last team retro, some expressed frustration about the nested nature of our epics - so I think unless there's a strong motivation for breaking it down further, keeping the tasks within a single epic makes more sense. Especially here - most of these these tasks are completely generic or redundant (releasing a new version doesn't require a new task).

**Comment by mostafa** [comment]
Sounds good! I'll merge them into the same ticket.

**Comment by mostafa** [comment]
Closed in favor of #124.
