### ISSUE TITLE
Release new version for pySigma 0.10.0

### ISSUE THREAD

**Issue by kelnage** [grafana/pySigma-backend-loki#77]
pySigma 0.10.0 was released 2023-07-30.

```[tasklist]
### Tasks
- [ ] Test our backend against the new version
- [ ] Fix any regressions
- [ ] Release a new version of our backend
```
